//-----------------------------------------------------------------------------

const UOBJ_PIECE           := 0x70b3;

const BROWN_PIECE          := 0x358B;
const LIGHT_PIECE          := 0x3584;
const CHECKER_PIECE_NAME   := "pionek";

const BROWN_PAWN           := 0x3590;
const LIGHT_PAWN           := 0x3589;
const PAWN_NAME            := "pionek";

const BROWN_BISHOP         := 0x358C;
const LIGHT_BISHOP         := 0x3585;
const BISHOP_NAME          := "goniec";

const BROWN_KNIGHT         := 0x358F;
const LIGHT_KNIGHT         := 0x3588;
const KNIGHT_NAME          := "kon";

const BROWN_ROOK           := 0x358D;
const LIGHT_ROOK           := 0x3586;
const ROOK_NAME            := "wieza";

const BROWN_QUEEN          := 0x3591;
const LIGHT_QUEEN          := 0x358A;
const QUEEN_NAME           := "krolowa";

const BROWN_KING           := 0x358E;
const LIGHT_KING           := 0x3587;
const KING_NAME            := "krol";

//-----------------------------------------------------------------------------
