//-----------------------------------------------------------------------------

const INSC_RUNEBOOK_DIFF     := 105;
const INSC_RUNEBOOK_SKPOINTS := 40;

//-----------------------------------------------------------------------------

const UOBJ_WRITING_DESK      := 0xB4A;
const UOBJ_RECALL_SCROLL     := 0x1f4c;
const UOBJ_GATE_SCROLL       := 0x1f60;

//-----------------------------------------------------------------------------

const INSCTYPE_SPELLS        := 1;
const INSCTYPE_SCROLLS       := 2;

const INSCRIPTION_CFG        := ":inscription:inscription";

//-----------------------------------------------------------------------------
