//================================================================================
//--------------------------------------------------------------------------------
// Animations
//--------------------------------------------------------------------------------
//================================================================================

const ANIM_WALK_UNARMED                := 0x0000; // Walk unarmed.
const ANIM_WALK_ARMED                  := 0x0001; // Walk armed.
const ANIM_RUN_UNARMED                 := 0x0002; // Run unarmed.
const ANIM_RUN_ARMED                   := 0x0003; // Run armed.
const ANIM_STAND                       := 0x0004; // Stand.
const ANIM_FIDGET_1                    := 0x0005; // Twist a little (look around?).
const ANIM_FIDGET_2                    := 0x0006; // Look down.
const ANIM_STAND_1HAND                 := 0x0007; // Stand 1 handed attack.
const ANIM_STAND_2HAND                 := 0x0008; // Stand 2 handed attack.
const ANIM_ATTACK_1HAND_WIDE           := 0x0009; // Attack 1 handed wide (sword/any).
const ANIM_ATTACK_1HAND_JAB            := 0x000a; // Attack 1 handed jab (fencing).
const ANIM_ATTACK_1HAND_DOWN           := 0x000b; // Attack 1 handed down (mace).
const ANIM_ATTACK_2HAND_DOWN           := 0x000c; // Attack 2 handed jab (mace).
const ANIM_ATTACK_2HAND_WIDE           := 0x000d; // Attack 2 handed wide.
const ANIM_ATTACK_2HAND_JAB            := 0x000e; // Attack 2 handed jab (spear).
const ANIM_HIT_NPC                     := 0x000f;
const ANIM_ATTACK_BOW                  := 0x0012; // Attack bow.
const ANIM_ATTACK_XBOW                 := 0x0013; // Attack xbow.
const ANIM_WALK_WARMODE                := 0x000f; // Walk in warmode.
const ANIM_CAST_DIR                    := 0x0010; // Spellcasting direction.
const ANIM_CAST_NPC                    := 0x000A; // Spellcasting npc.
const ANIM_CAST_AREA                   := 0x0011; // Spellcasting area.
const ANIM_HIT                         := 0x0014; // Get hit.
const ANIM_DIE_BACK                    := 0x0015; // Die backward.
const ANIM_DIE_FOR                     := 0x0016; // Die forward.
const ANIM_BOW                         := 0x0020; // Bow.
const ANIM_SALUTE                      := 0x0021; // Salute.
const ANIM_EAT                         := 0x0022; // Eat.
const ANIM_CAST_WEARWOLF               := 0x0011;
const ANIM_STUMBLE                     := 0x000a;
const ANIM_NPC_IDLE                    := 0x000b;
const ANIM_NPC_FIDGET1                 := 0x0011;
const ANIM_NPC_FIDGET2                 := 0x0012;
const ANIM_NPC_EAT                     := 0x000f;
const ANIM_NPC_LIEDOWN                 := 0x000b;

//--------------------------------------------------------------------------------
