//================================================================================
//--------------------------------------------------------------------------------
// Creature Ids
//--------------------------------------------------------------------------------
//================================================================================

const CID_OGRE                         := 0x0001;  // Ogre.
const CID_LBR_OGRE                     := 0x0053;
const CID_ZOMBIE                       := 0x0003;  // Zombie.
const CID_GARGOYLE                     := 0x0004;  // Gargoyle.
const CID_EAGLE                        := 0x0005;  // Eagle.
const CID_BIRD                         := 0x0006;  // Bird.
const CID_CORPSER                      := 0x0008;  // Corpser.
const CID_DAEMON                       := 0x0009;  // Daemon.
const CID_DAEMON_SWORD                 := 0x000a;  // Daemon with sword.
const CID_DRAGON_RED                   := 0x003b;
const CID_DRAGON_GREY                  := 0x000c;  // Dragon grey.
const CID_AIR_ELEMENTAL                := 0x000d;  // Air Elemental.
const CID_EARTH_ELEMENTAL              := 0x000e;  // Earth Elemental.
const CID_FIRE_ELEMENTAL               := 0x000f;  // Fire Elemental.
const CID_WATER_ELEMENTAL              := 0x0010;  // Water elemental.
const CID_ORC                          := 0x0011;  // Orc.
const CID_ORC_CLUB                     := 0x0029;
const CID_ORC_LORD                     := 0x0007;  // Orc Lord.
const CID_ETTIN                        := 0x0002;  // Ettin.
const CID_ETTIN_AXE                    := 0x0012;  // Ettin with axe.
const CID_GIANT_SNAKE                  := 0x0015;  // Giant
const CID_CROW                         := 0x011b;

const CID_HUMAN_MALE                   := 0x0190;
const CID_HUMAN_FEMALE                 := 0x0191;
const CID_ELF_MALE                     := 0x025D;
const CID_ELF_FEMALE                   := 0x025E;
const CID_GHOST                        := 0x0192;
const CID_FEMALE_GHOST                 := 0x0193;
const CID_ELF_GHOST                    := 0x025F;
const CID_ELF_FGHOST                   := 0x0260;
const CID_GM                           := 0x03db;
const CID_WEARWOLF                     := 0x00F1;  //0x002a;
const CID_WOLF                         := 0x00e1;
const CID_DIREWOLF                     := 0x0017;
const CID_FROSTWOLF                    := 0x0064;
const CID_GRIZZLY                      := 0xD4;

const CID_LICHE                        := 0x0018;

const CID_LIZARD                       := 0x0021;
const CID_LIZARD_MACE                  := 0x0024;
const CID_LIZARD_SPEAR                 := 0x0023;
const CID_VAMPIRE                      := 0x007c;
const CID_VAMP_BAT                     := 0x013D;
const CID_VAMP_GARGOYLE                := 0x02F2;

const CID_COW1                         := 0x00d8;
const CID_COW2                         := 0x00e7;

const CID_RATMAN                       := 0x002a;
const CID_RATMAN_SWORD                 := 0x002d;
const CID_RATMAN_AXE                   := 0x002c;

const CID_GREATWYRM                    := 0x031e;

const CID_ARMORED_NIGHTMARE            := 0x011c;


//-----------------------------------------------------------------------------

const CID_GOLEM                        := 0x02F0;
const CID_LLAMAPACK                    := 0x0124;
const CID_BEIGE_HORSE                  := 0x00C8;
const CID_HORSEPACK                    := 0x0123;
const CID_LLAMA                        := 0x00DC;

//--------------------------------------------------------------------------------
