//================================================================================
//--------------------------------------------------------------------------------
// Skill IDs
//--------------------------------------------------------------------------------
//================================================================================

const SKILLID_ALCHEMY                  := 0;
const SKILLID_ANATOMY                  := 1;
const SKILLID_ANIMALLORE               := 2;
const SKILLID_ITEMID                   := 3;
const SKILLID_ARMORER                  := 4;
const SKILLID_PARRY		                 := 5;
const SKILLID_BEGGING                  := 6;
const SKILLID_BLACKSMITHY              := 7;
const SKILLID_BOWCRAFT                 := 8;
const SKILLID_PEACEMAKING              := 9;
const SKILLID_INSIGHT                  := 10;
const SKILLID_CARPENTRY                := 11;
const SKILLID_CARTOGRAPHY              := 12;
const SKILLID_COOKING                  := 13;
const SKILLID_DETECTINGHIDDEN          := 14;
const SKILLID_ENTICEMENT               := 15;
const SKILLID_EVALINT                  := 16;
const SKILLID_HEALING                  := 17;
const SKILLID_FISHING                  := 18;
const SKILLID_DRUID                    := 19;
const SKILLID_HERDING                  := 20;
const SKILLID_HIDING                   := 21;
const SKILLID_PROVOCATION              := 22;
const SKILLID_INSCRIPTION              := 23;
const SKILLID_LOCKPICKING              := 24;
const SKILLID_MAGERY                   := 25;
const SKILLID_MAGICRESISTANCE          := 26;
const SKILLID_TACTICS                  := 27;
const SKILLID_SNOOPING                 := 28;
const SKILLID_MUSICIANSHIP             := 29;
const SKILLID_POISONING                := 30;
const SKILLID_ARCHERY                  := 31;
const SKILLID_SPIRITSPEAK              := 32;
const SKILLID_STEALING                 := 33;
const SKILLID_TAILORING                := 34;
const SKILLID_TAMING                   := 35;
const SKILLID_FARMING                  := 36;
const SKILLID_TINKERING                := 37;
const SKILLID_TRACKING                 := 38;
const SKILLID_VETERINARY               := 39;
const SKILLID_SWORDSMANSHIP            := 40;
const SKILLID_MACEFIGHTING             := 41;
const SKILLID_FENCING                  := 42;
const SKILLID_WRESTLING                := 43;
const SKILLID_LUMBERJACKING            := 44;
const SKILLID_MINING                   := 45;
const SKILLID_MEDITATION               := 46;
const SKILLID_STEALTH                  := 47;
const SKILLID_WEARWOLF                 := 48;
const SKILLID_NECRO                    := 49;
const SKILLID_VAMPIRE                  := 50;
const SKILLID_MAGICITEMMAKING          := 51;
const SKILLID_BARBARIAN                := 52;
const SKILLID_AXESMANSHIP              := 53;
const SKILLID_HUNTER                   := 54;
const SKILLID_ZEAL                     := 55;
const SKILLID_PALADINISM               := 56;
const SKILLID_FANATICISM               := 57;
const SKILLID_KENSAI                   := 58;

const SKILLID__NORMAL_HIGHEST          := 51;
const SKILLID__HIGHEST                 := 58;

//
const SECOND_SKILL_GAIN_MOD            := 1.75;
//

//================================================================================
//--------------------------------------------------------------------------------
// Inscription Sounds & Effects
//--------------------------------------------------------------------------------
//================================================================================

Const SOUND_EFFECT_INSCRIPTION         := 0x50;
Const SOUND_EFFECT_SCRIBE              := 0x24A;
Const SOUND_EFFECT_SPARKLE             := 0x1e8;
Const EFFECT_SPARKLE_I                 := 0x373a;

//================================================================================
//--------------------------------------------------------------------------------
// Alchemy Sounds & Effects
//--------------------------------------------------------------------------------
//================================================================================

const POISON_SOUND                     := 0x247;
const DRINK_SOUND                      := 0x32;
const EFFECT_BLUE_SPARKLE              := 0x373a;
const SOUND_EFFECT_CURE	               := 0x1e1;
const EFFECT_SPARKLE                   := 0x374a;
const HIT_ACTION                       := 0x148b;
const SOUND_EFFECT_EXPLOSION	       := 0x208;
const SOUND_EFFECT_HEAL	               := 0x1f3;
const EFFECT_EXPLOSION                 := 0x36b0;

//================================================================================
//--------------------------------------------------------------------------------
// Resurrect Field Sounds & Effects
//--------------------------------------------------------------------------------
//================================================================================

const EFFECT_SPARKLE_RES               := 0x373a;
const SOUND_EFFECT_RES                 := 0x215;

//--------------------------------------------------------------------------------
