//================================================================================
//--------------------------------------------------------------------------------
// Graphical Effects
//--------------------------------------------------------------------------------
//================================================================================

const FX_SPLASH                        := 0x352d; //
const FX_EXPLODE_1                     := 0x36cb; //
const FX_EXPLODE_2                     := 0x36bd; //
const FX_EXPLODE_3                     := 0x36b0; //
const FX_FIREBALL                      := 0x36d4; //
const FX_MAGIC_ARROW                   := 0x36e4; //
const FX_FIRE_BOLT                     := 0x36f4; // Firesnake. (pagan?)
const FX_EXPLODE_BALL                  := 0x36fe; // Not used.

const FX_FLAMESTRIKE                   := 0x3709; //
const FX_SMOKE                         := 0x3728;
const FX_TELE_VANISH                   := 0x372a; // Teleport vanish.
const FX_SPELL_FAIL                    := 0x3735; //
const FX_BLESS_EFFECT                  := 0x373a; //
const FX_CURSE_EFFECT                  := 0x374a; //
const FX_SPARK_EFFECT                  := 0x375a; //
const FX_HEAL_EFFECT                   := 0x376a; //
const FX_MARK_EFFECT                   := 0x3779;
const FX_BLUEMOONSTART                 := 0x3789; // Deathvortex?
const FX_ENERGY_BOLT                   := 0x379f; //
const FX_BLADES_EMERGE                 := 0x37a0; // Not used.
const FX_GLOW                          := 0x37b9; // Not used.
const FX_GLOW_SPIKE                    := 0x37c4; // Not used.
const FX_DEATH_FUNNEL                  := 0x37cc; //
const FX_BLADES                        := 0x37eb; //
const FX_STATIC                        := 0x3818; // Not used. (pink static)
const FX_POISON_F_EW                   := 0x3914; // Poison field.
const FX_POISON_F_NS                   := 0x3920; // Poison field.
const FX_ENERGY_F_EW                   := 0x3947; // Energy field.
const FX_ENERGY_F_NS                   := 0x3956; // Energy field.
const FX_PARA_F_EW                     := 0x3967; // Paralyze field.
const FX_PARA_F_NS                     := 0x3979; // Paralyze field.
const FX_FIRE_F_EW                     := 0x398c; // Fire field.
const FX_FIRE_F_NS                     := 0x3996; // Fire field.
const FX_POISON_GAS                    := 0x113a; // Gas

//--------------------------------------------------------------------------------
