//-----------------------------------------------------------------------------
// Magic
//-----------------------------------------------------------------------------

const UOBJ_SPELLBOOK                   := 0x0efa;
const UOBJ_RUNEBOOK                    := 0x6300;
const UOBJ_RECALLSCROLL                := 0x1F4C;
const UOBJ_WAND_START                  := 0x6110;
const UOBJ_WAND_END                    := 0x614f;
const UOBJ_RUNE                        := 0x1f14;
const UOBJ_RUNE2                       := 0x1f15;
const UOBJ_RETURN_RUNE                 := 0xA29C;
const UOBJ_MAGICTRENORB                := 0xa370;
const UOBJ_WAND                        := 0xDF3;
const UOBJ_MAGICMAKEWAND               := 0xA304;

//-----------------------------------------------------------------------------
// Druid
//-----------------------------------------------------------------------------

const UOBJ_DRUID_BAG                   := 0x706b;
const UOBJ_DRUID_STAFF                 := 0x7068;
const UOBJ_DRUID_RING                  := 0x7069;
const UOBJ_DRUID_ROBE                  := 0x708e;

//-----------------------------------------------------------------------------
// Necro
//-----------------------------------------------------------------------------

const UOBJ_NECROBOOK                   := 0xD100;
const UOBJ_NECRO_STAFF                 := 0xA151;
const UOBJ_NECRO_ROBE                  := 0xA15A;
const UOBJ_NECROSCROLL_START           := 0xa101;
const UOBJ_NECROSCROLL_END             := 0xa110;
const UOBJ_NECRO_RING                  := 0xA154;

//-----------------------------------------------------------------------------
// Vampire
//-----------------------------------------------------------------------------

const UOBJ_VAMPHOUSE_1                 := 0x6239;
const UOBJ_VAMPHOUSE_2                 := 0x623A;
const UOBJ_VAMPMANOR                   := 0x6264;

const UOBJ_CRYSTAL_BALL                := 0x0E2D;

const UOBJ_VAMP_BLOOD                  := 0xA800;
const UOBJ_VAMP_BAG                    := 0xA801;
const UOBJ_VAMP_STAFF                  := 0xA802;
const UOBJ_VAMP_RING                   := 0xA803;
const UOBJ_VAMP_ROBE                   := 0xA804;
const UOBJ_VAMP_RUNE_SET               := 0xA810;
const UOBJ_VAMP_RUNE_END               := 0xA81F;
const UOBJ_VAMPWAR_RUNE_SET            := 0xA830;
const UOBJ_VAMPWAR_RUNE_END            := 0xA83B;

//-----------------------------------------------------------------------------
// WearWolf
//-----------------------------------------------------------------------------

const UOBJ_TOTEMSKALP                  := 0xA723;
const UOBJ_WWOLF_RUNE_SET              := 0xA700;
const UOBJ_WWOLF_RUNE_END              := 0xA714;

//-----------------------------------------------------------------------------
// Paladin & Dark Knight
//-----------------------------------------------------------------------------

const UOBJ_PD_WCBOOK                   := 0xA850;
const UOBJ_PD_SHIELD                   := 0xA851;
const UOBJ_HOLYWATER                   := 0xA852;
const UOBJ_PD_ALTAR                    := 0xA853;

const UOBJ_DK_WCBOOK                   := 0xA880;
const UOBJ_DK_SHIELD                   := 0xA881;
const UOBJ_DK_ALTAR                    := 0xA883;

//-----------------------------------------------------------------------------
