//-----------------------------------------------------------------------------
// Tools
//-----------------------------------------------------------------------------

const UOBJ_TINKER_TOOLS                := 0x1ebc;
const UOBJ_KOSA                        := 0x9000;
const UOBJ_SHOVEL                      := 0x0f39;
const UOBJ_PICKAXE                     := 0x0e85;
const UOBJ_SCOOP                       := 0x10e7;

//-----------------------------------------------------------------------------
// Crafting-Needed Items
//-----------------------------------------------------------------------------

const UOBJ_THREAD                      := 0x0fa0;
const UOBJ_YARN                        := 0x0E1F;
const UOBJ_WHELL_START                 := 0x1015;
const UOBJ_WHELL_END                   := 0x101e;
const UOBJ_WHELL_START2                := 0x10a4;
const UOBJ_WHELL_END2                  := 0x10a6;

const UOBJ_ANVIL1                      := 0x0faf;
const UOBJ_ANVIL2                      := 0x0fb0;
const UOBJ_SMALL_FORGE                 := 0x0fb1;

const UOBJ_FORGE_START                 := 0x197a;
const UOBJ_FORGE_END                   := 0x19a9;

const UOBJ_LOOM_START                  := 0x105f;
const UOBJ_LOOM_END                    := 0x1066;

const UOBJ_SCISSORS                    := 0x0F9E;

//-----------------------------------------------------------------------------
// Alchemy
//-----------------------------------------------------------------------------

const UOBJ_EMPTY_BOTTLE                := 0x0f0e;
const UOBJ_VIAL                        := 0xe24;
const UOBJ_POTION_KEG                  := 0x1940;

const UOBJ_LESSER_HEAL_POTION          := 0xDC01;
const UOBJ_HEAL_POTION                 := 0xDC02;
const UOBJ_GREATER_HEAL_POTION         := 0xDC03;
const UOBJ_LESSER_POISON_POTION        := 0xDC04;
const UOBJ_POISON_POTION               := 0xDC05;
const UOBJ_GREATER_POISON_POTION       := 0xDC06;
const UOBJ_DEADLY_POISON_POTION        := 0xDC17;
const UOBJ_LESSER_EXPLOSION_POTION     := 0xDC08;
const UOBJ_EXPLOSION_POTION            := 0xDC09;
const UOBJ_GREATER_EXPLOSION_POTION    := 0xDC07;
const UOBJ_LESSER_AGILITY_POTION       := 0xDC0B;
const UOBJ_AGILITY_POTION              := 0xDC0C;
const UOBJ_GREATER_AGILITY_POTION      := 0xDC0D;
const UOBJ_REFRESH_POTION              := 0xDC0E;
const UOBJ_FULL_REFRESH_POTION         := 0xDC0F;
const UOBJ_LESSER_STRENGTH_POTION      := 0xDC10;
const UOBJ_STRENGTH_POTION             := 0xDC11;
const UOBJ_GREATER_STRENGTH_POTION     := 0xDC12;
const UOBJ_NIGHTSIGHT_POTION           := 0xDCE6;
const UOBJ_BLIND_POTION                := 0xDCE7;
const UOBJ_LESSER_CURE_POTION          := 0xDC14;
const UOBJ_CURE_POTION                 := 0xDC15;
const UOBJ_GREATER_CURE_POTION         := 0xDC16;
const UOBJ_MANA_POTION                 := 0xDCE8;
const UOBJ_PROTPOISON_POTION           := 0xDCE9;
const UOBJ_POLYMORPH_POTION            := 0xDCF0;
const UOBJ_DISPERSION_POTION           := 0xDCE5;
const UOBJ_LESSER_CURSE_POTION         := 0xDCF1;
const UOBJ_CURSE_POTION                := 0xDCF2;
const UOBJ_GREATER_CURSE_POTION        := 0xDCF3;
const UOBJ_WEARWOLF_CURE_POTION        := 0xDCF4;
const UOBJ_LIGHT_LIFE_ELIXIR           := 0xDCF5;
const UOBJ_LIFE_ELIXIR                 := 0xDCF6;
const UOBJ_LIGHT_MANA_ELIXIR           := 0xDCF7;
const UOBJ_MANA_ELIXIR                 := 0xDCF8;
const UOBJ_LIGHT_STAMINA_ELIXIR        := 0xDCF9;
const UOBJ_STAMINA_ELIXIR              := 0xDCFA;
const UOBJ_VAMPIRE_CURE_POTION         := 0xDCFB;
const UOBJ_LESSER_HOLY_POTION          := 0xDCFC;
const UOBJ_HOLY_POTION                 := 0xDCFD;
const UOBJ_GREATER_HOLY_POTION         := 0xDCFE;
const UOBJ_LESSER_AGGRO_OIL_POTION     := 0xDC19;
const UOBJ_AGGRO_OIL_POTION            := 0xDC18;

const UOBJ_GRAPE                       := 0x0d1a;
const UOBJ_HOPE                        := 0x1aa2;
const UOBJ_APPLE                       := 0x09d0;
const UOBJ_HONEYDEW                    := 0x0c74;

const UOBJ_BEER                        := 0x1f96;
const UOBJ_WINE                        := 0x1f9c;
const UOBJ_CIDER                       := 0x1f98;
const UOBJ_EMPTYPITCHER                := 0x0ff6;
const UOBJ_EMPTYGLASS                  := 0x1f82;

//-----------------------------------------------------------------------------
// Musicanship
//-----------------------------------------------------------------------------

const UOBJ_DRUM                        := 0x0e9c;
const UOBJ_TAMB                        := 0x0e9d;
const UOBJ_HARP                        := 0x0eb2;
const UOBJ_LUTE                        := 0x0eb3;

const UOBJ_BARDBOOK                    := 0xA000;

//-----------------------------------------------------------------------------
// Carpets
//-----------------------------------------------------------------------------

const UOBJ_TWINE                      := 0xa501;
const UOBJ_RRED_CARPET                 := 0xa511;
const UOBJ_RBLUE_CARPET                := 0xa512;
const UOBJ_RBRONZE_CARPET              := 0xa513;
const UOBJ_RBLUE2_CARPET               := 0xa514;
const UOBJ_RBEZOWY_CARPET              := 0xa515;
const UOBJ_RCBEZOWY_CARPET             := 0xa516;

const UOBJ_TAPESTRY1                   := 0x0FD6;
const UOBJ_ROLLEDTAP1                  := 0xa521;
const UOBJ_ROLLEDTAP2                  := 0xa522;
const UOBJ_ROLLEDTAP3                  := 0xa523;

//-----------------------------------------------------------------------------
// Painting
//-----------------------------------------------------------------------------

const UOBJ_EASEL                       := 0x0F65;
const UOBJ_MATEASEL                    := 0x0F66;
const UOBJ_PAINTBRUSH                  := 0x0FC1;
const UOBJ_PAINTMAT                    := 0xb100;
const UOBJ_PORTRAIT                    := 0xB101;

//-----------------------------------------------------------------------------
// Fishing
//-----------------------------------------------------------------------------

const UOBJ_SPLASH_TILE                 := 0x706c;

const UOBJ_FISHSTEAK                   := 0x097a;
const UOBJ_COOKEDFISHSTEAK             := 0x097b;

const UOBJ_BLACKPEARL                  := 0x0f7a;
const UOBJ_OYSTER                      := 0xc73a;
const UOBJ_BLACKMOOR                   := 0x0F79;

//-----------------------------------------------------------------------------
// Tinkering
//-----------------------------------------------------------------------------

const UOBJ_CALENDAR                    := 0x5016;
const UOBJ_CLOCK                       := 0x104c;
const UOBJ_CLOCK_FRAME                 := 0x104e;
const UOBJ_CLOCK_PARTS                 := 0x104f;
const UOBJ_AXLE_AND_GEARS              := 0x1051;
const UOBJ_GEARS                       := 0x1053;
const UOBJ_HINGE                       := 0x1055;
const UOBJ_SEXTANT                     := 0x1057;
const UOBJ_SEXTANT_PARTS               := 0x1059;
const UOBJ_AXLE                        := 0x105b;
const UOBJ_SPRINGS                     := 0x105d;
const UOBJ_CLAWS                       := 0xA230;

//-----------------------------------------------------------------------------
// Mining
//-----------------------------------------------------------------------------

const UOBJ_ORES_START                  := 0x6500;
const UOBJ_ORES_END                    := 0x6515;

const UOBJ_INGOTS_START                := 0x6530;
const UOBJ_INGOTS_END                  := 0x6543;
const UOBJ_ALL_INGOTS_END              := 0x6545;

const UOBJ_IRON_ORE                    := 0x6500;
const UOBJ_SILVER_ORE                  := 0x650A;
const UOBJ_GOLDM_ORE                   := 0x650B;
const UOBJ_BLACKROCK_ORE               := 0x650C;
const UOBJ_AGAPITE_ORE                 := 0x650D;
const UOBJ_VALORITE_ORE                := 0x650E;
const UOBJ_VERITE_ORE                  := 0x650F;
const UOBJ_MYTHERIL_ORE                := 0x6510;
const UOBJ_BLOODROCK_ORE               := 0x6511;
const UOBJ_AZURITE_ORE                 := 0x6512;
const UOBJ_ROYAL_ORE                   := 0x6513;
const UOBJ_MYSTIC_ORE                  := 0x6515;

const UOBJ_IRON_INGOT                  := 0x6530;
const UOBJ_SILVER_INGOT	               := 0x653A;
const UOBJ_GOLDM_INGOT	               := 0x653B;
const UOBJ_BLACKROCK_INGOT             := 0x653C;
const UOBJ_AGAPITE_INGOT               := 0x653D;
const UOBJ_VALORITE_INGOT              := 0x653E;
const UOBJ_VERITE_INGOT	               := 0x653F;
const UOBJ_MYTHERIL_INGOT              := 0x6540;
const UOBJ_BLOODROCK_INGOT             := 0x6541;
const UOBJ_AZURITE_INGOT               := 0x6542;
const UOBJ_ROYAL_INGOT                 := 0x6543;
const UOBJ_MYSTIC_INGOT                := 0x6545;
const UOBJ_GRAFIT_INGOT                := 0x6544;

const UOBJ_GOLD_INGOT                  := 0x1be9;
const UOBJ_SILVERM_INGOT               := 0x1bf5;

const UOBJ_GLASS                       := 0xee20;
const UOBJ_CLAY                        := 0xee19;
const UOBJ_SAND                        := 0xee18;

const UOBJ_CRYSTAL                     := 0x6546;

const UOBJ_GOLD_COINS                  := 0x0eed;
const UOBJ_SILVER_COINS                := 0x0ef2;

//-----------------------------------------------------------------------------
// Lumberjacking
//-----------------------------------------------------------------------------

const UOBJ_NORMALLOG                   := 0x1BDD;
const UOBJ_CEDARLOG                    := 0x6700;
const UOBJ_OAKLOG                      := 0x6701;
const UOBJ_WALNUTLOG                   := 0x6702;
const UOBJ_WILLOWLOG                   := 0x6703;
const UOBJ_CYPRESSLOG                  := 0x6704;
const UOBJ_YEWLOG                      := 0x6705;
const UOBJ_OHIILOG                     := 0x6706;
const UOBJ_MYSTICLOG                   := 0x6707;

const UOBJ_NORMALBOARD                 := 0x1BD7;
const UOBJ_CEDARBOARD                  := 0x6710;
const UOBJ_OAKBOARD                    := 0x6711;
const UOBJ_WALNUTBOARD                 := 0x6712;
const UOBJ_WILLOWBOARD                 := 0x6713;
const UOBJ_CYPRESSBOARD                := 0x6714;
const UOBJ_YEWBOARD                    := 0x6715;
const UOBJ_OHIIBOARD                   := 0x6716;
const UOBJ_MYSTICBOARD                 := 0x6717;

//-----------------------------------------------------------------------------
// Tailoring
//-----------------------------------------------------------------------------

const UOBJ_NORMALHIDE                  := 0x1078;
const UOBJ_BLACKHIDE                   := 0x6750;
const UOBJ_SNOWHIDE                    := 0x6751;
const UOBJ_ICEHIDE                     := 0x6752;
const UOBJ_STONEHIDE                   := 0x6753;
const UOBJ_FIREHIDE                    := 0x6754;
const UOBJ_MYSTICHIDE                  := 0x675a;
const UOBJ_DAEMONHIDE				   := 0xF127;

const UOBJ_NORMALLEATHER               := 0x1067;
const UOBJ_BLACKLEATHER                := 0x6755;
const UOBJ_SNOWLEATHER                 := 0x6756;
const UOBJ_ICELEATHER                  := 0x6757;
const UOBJ_STONELEATHER                := 0x6758;
const UOBJ_FIRELEATHER                 := 0x6759;
const UOBJ_MYSTICLEATHER               := 0x675b;
const UOBJ_DAEMONLEATHER			   := 0xF128;

const UOBJ_SEWING_KIT                  := 0x0f9d;
const UOBJ_BOLT_START                  := 0x0f95;
const UOBJ_BOLT_END                    := 0x0f9c;
const UOBJ_CLOTH_STARTS                := 0x175d;
const UOBJ_CLOTH_END                   := 0x1768;
const UOBJ_TKANINA                     := 0x1766;
const UOBJ_TKANINA2                    := 0x1768;

const UOBJ_POTOFOIL                    := 0x6770;

//-----------------------------------------------------------------------------
// Herding
//-----------------------------------------------------------------------------

const UOBJ_BEEHEEVE                    := 0x091a;
const UOBJ_BBEEHEEVE                   := 0x03a5;
const UOBJ_BIGBEES                     := 0x091b;
const UOBJ_SMALLBEES                   := 0x0923;
const UOBJ_BEEHEEVEDEED                := 0xa299;
const UOBJ_HONEY                       := 0x9ec;
const UOBJ_WOSK                        := 0x1422;
const UOBJ_POTOFVAX                    := 0x142a;
const UOBJ_STICK                       := 0x1429;
const UOBJ_ROLLSTICK                   := 0x1420;

//-----------------------------------------------------------------------------
// Cooking
//-----------------------------------------------------------------------------

const UOBJ_CAULDRON                    := 0x0974;
const UOBJ_CAULDRON2                   := 0x0975;

const UOBJ_CLEAVER                     := 0x0EC2;
const UOBJ_SKINNINGKNIFE               := 0xEC4;
//-----------------------------------------------------------------------------
