//--------------------------------------------------------------------------------

const CORE_SETTINGS_MIN_ATTRIBUTE  := 0;
const CORE_SETTINGS_MAX_ATTRIBUTE  := 4000;  // przez system setnych w statystykach raw musi zostac zmienione na 200
const CORE_SETTINGS_MIN_VITAL      := 100;
const CORE_SETTINGS_MAX_VITAL      := 10000000;
const CORE_SETTINGS_MIN_REGEN_RATE := -30000;
const CORE_SETTINGS_MAX_REGEN_RATE := 30000;

const PROP_STATCAP                 := "StatCap";
const PROP_SKILLCAP                := "SkillCap";
const PROP_STATSUM                 := "StSum";
const PROP_SKILLSUM                := "SkSum";

const ATTRIBUTEID_ALCHEMY          := "Alchemy";
const ATTRIBUTEID_ANATOMY          := "Anatomy";
const ATTRIBUTEID_ANIMALLORE       := "AnimalLore";
const ATTRIBUTEID_ITEMID           := "ItemId";
const ATTRIBUTEID_ARMSLORE         := "ArmsLore";
const ATTRIBUTEID_PARRY            := "Parry";
const ATTRIBUTEID_BEGGING          := "Begging";
const ATTRIBUTEID_BLACKSMITHY      := "Blacksmithy";
const ATTRIBUTEID_BOWCRAFT         := "Bowcraft";
const ATTRIBUTEID_PEACEMAKING      := "Peacemaking";
const ATTRIBUTEID_INSIGHT          := "Insight";
const ATTRIBUTEID_CARPENTRY        := "Carpentry";
const ATTRIBUTEID_CARTOGRAPHY      := "Cartography";
const ATTRIBUTEID_COOKING          := "Cooking";
const ATTRIBUTEID_DETECTINGHIDDEN  := "DetectingHidden";
const ATTRIBUTEID_ENTICEMENT       := "Enticement";
const ATTRIBUTEID_EVALINT    	     := "EvaluatingIntelligence";
const ATTRIBUTEID_HEALING          := "Healing";
const ATTRIBUTEID_FISHING          := "Fishing";
const ATTRIBUTEID_DRUID            := "Druid";
const ATTRIBUTEID_HERDING          := "Herding";
const ATTRIBUTEID_HIDING           := "Hiding";
const ATTRIBUTEID_PROVOCATION      := "Provocation";
const ATTRIBUTEID_INSCRIPTION      := "Inscription";
const ATTRIBUTEID_LOCKPICKING      := "Lockpicking";
const ATTRIBUTEID_MAGERY           := "Magery";
const ATTRIBUTEID_MAGICRESISTANCE  := "MagicResistance";
const ATTRIBUTEID_TACTICS          := "Tactics";
const ATTRIBUTEID_SNOOPING         := "Snooping";
const ATTRIBUTEID_MUSICIANSHIP     := "Musicianship";
const ATTRIBUTEID_POISONING        := "Poisoning";
const ATTRIBUTEID_ARCHERY          := "Archery";
const ATTRIBUTEID_SPIRITSPEAK      := "SpiritSpeak";
const ATTRIBUTEID_STEALING         := "Stealing";
const ATTRIBUTEID_TAILORING        := "Tailoring";
const ATTRIBUTEID_TAMING           := "AnimalTaming";
const ATTRIBUTEID_FARMING          := "Farming";
const ATTRIBUTEID_TINKERING        := "Tinkering";
const ATTRIBUTEID_TRACKING         := "Tracking";
const ATTRIBUTEID_VETERINARY       := "Veterinary";
const ATTRIBUTEID_SWORDSMANSHIP    := "Swordsmanship";
const ATTRIBUTEID_MACEFIGHTING     := "Macefighting";
const ATTRIBUTEID_FENCING          := "Fencing";
const ATTRIBUTEID_WRESTLING        := "Wrestling";
const ATTRIBUTEID_LUMBERJACKING    := "Lumberjacking";
const ATTRIBUTEID_MINING           := "Mining";
const ATTRIBUTEID_MEDITATION       := "Meditation";
const ATTRIBUTEID_STEALTH          := "Stealth";
const ATTRIBUTEID_WEARWOLF         := "Wearwolf";
const ATTRIBUTEID_NECRO            := "Necromancy";
const ATTRIBUTEID_VAMPIRE          := "Vampire";
const ATTRIBUTEID_MAGICITEMMAKING  := "MagicItemMaking";
const ATTRIBUTEID_PAINTING         := "Painting";
const ATTRIBUTEID_HUNTER           := "Hunter";
const ATTRIBUTEID_ZEAL             := "Zeal";
const ATTRIBUTEID_PALADINISM       := "Paladinism";
const ATTRIBUTEID_FANATICISM       := "Fanaticism";
const ATTRIBUTEID_AXESMANSHIP      := "Axesmanship";

const ATTRIBUTEID_DEXTERITY        := "Dexterity";
const ATTRIBUTEID_INTELLIGENCE     := "Intelligence";
const ATTRIBUTEID_STRENGTH         := "Strength";
const VITALID_LIFE                 := "Life";
const VITALID_MANA                 := "Mana";
const VITALID_STAMINA              := "Stamina";

//-----------------------------------------------------------------------------

const LAST_USE_TARGET              := 1;
const LAST_USE_SKILL               := 2;

//--------------------------------------------------------------------------------
