//=====================================================================
//---------------------------------------------------------------------
// Uo Files & Patch
//---------------------------------------------------------------------
//=====================================================================

const MAX_LASTLOGIPS                   := 500;

//--------------------------------------------------------------------------------

const CUODMR_CMD_FILE                   := 9;
const CUODMR_CMD_VERCLIENT              := 8;
const CUODMR_CMD_GENID                  := 7;
const CUODMR_CMD_GID                    := 6;
const CUODMR_CMD_SINFO                  := 5;
const CUODMR_CMD_FILES                  := 4;
const CUODMR_CMD_VER                    := 3;
const CUODMR_CMD_MOD                    := 2;
const CUODMR_CMD_PROC                   := 1;

const UOL_VERSION                       := 0x1;

const CUO_MAP_FILE                     := 1;
const CUO_STC_FILE                     := 2;
const CUO_ART_FILE                     := 3;
const CUO_ANM_FILE                     := 4;
const CUO_SND_FILE                     := 5;
const CUO_TEX_FILE                     := 6;
const CUO_GMP_FILE                     := 7;
const CUO_MLT_FILE                     := 8;
const CUO_SKL_FILE                     := 9;
const CUO_TLD_FILE                     := 10;
const CUO_AMD_FILE                     := 11;
const CUO_VDT_FILE                     := 12;

const CUO_MAP0_MUL                     := "map0.mul";
const CUO_MAP1_MUL                     := "map1.mul";
const CUO_MAP2_MUL                     := "map2.mul";
const CUO_MAP3_MUL                     := "map3.mul";

const CUO_GMP_MUL                      := "gumpart.mul";
const CUO_GMP_IDX                      := "gumpidx.mul";

const CUO_ART_MUL                      := "art.mul";
const CUO_ART_IDX                      := "artidx.mul";

const CUO_ANM_MUL                      := "anim.mul";
const CUO_ANM_IDX                      := "anim.idx";

const CUO_ANM2_MUL                     := "anim2.mul";
const CUO_ANM2_IDX                     := "anim2.idx";

const CUO_ANM3_MUL                     := "anim3.mul";
const CUO_ANM3_IDX                     := "anim3.idx";

const CUO_SND_MUL                      := "sound.mul";
const CUO_SND_IDX                      := "soundidx.mul";

const CUO_STC0_MUL                     := "statics0.mul";
const CUO_STC0_IDX                     := "staidx0.mul";

const CUO_STC1_MUL                     := "statics1.mul";
const CUO_STC1_IDX                     := "staidx1.mul";

const CUO_STC2_MUL                     := "statics2.mul";
const CUO_STC2_IDX                     := "staidx2.mul";

const CUO_STC3_MUL                     := "statics3.mul";
const CUO_STC3_IDX                     := "staidx3.mul";

const CUO_MLT_MUL                      := "multi.mul";
const CUO_MLT_IDX                      := "multi.idx";

const CUO_SKL_MUL                      := "skills.mul";
const CUO_SKL_IDX                      := "skills.idx";

const CUO_VDT_MUL                      := "verdata.mul";

const CUO_TLD_MUL                      := "tiledata.mul";

//=====================================================================
//---------------------------------------------------------------------
// FOrbidden Progs
//---------------------------------------------------------------------
//=====================================================================

const ADREN3_SIZE                      := 73728;
const ADREN3_SIZE1                     := 73216;
const ADREN3_SIZE2                     := 93696;
const ADREN3_NAME                      := "adrenaline";

const VELOCITY_SIZE                    := 144384;
const VELOCITY_NAME                    := "velocity";

const NINJA_SIZE                       := 88576;
const NINJA_NAME                       := "ninja";

const GESTURE_SIZE                     := 109568;
const GESTURE_NAME                     := "gesture";

const TEXTER_SIZE                      := 212480;
const TEXTER_NAME                      := "texter";

const COLORCONF_SIZE                   := 114688;
const COLORCONF_NAME                   := "colorconf";

//---------------------------------------------------------------------
