//=============================================================================
//-----------------------------------------------------------------------------
// Moving
//-----------------------------------------------------------------------------
//=============================================================================

const MOVETYPE_ALL           := -1;
const MOVETYPE_NORMAL        := 0;
const MOVETYPE_PORTAL        := 1;
const MOVETYPE_TELE          := 2;
const MOVETYPE_MOONGATE      := 3;
const MOVETYPE_CMD           := 4;

const MOVELOC_DELAY          := 2;

const MOVEITEM_NORMAL        := MOVEOBJECT_NORMAL;
const MOVEITEM_FORCELOCATION := MOVEOBJECT_FORCELOCATION;
const MOVECHAR_FORCELOCATION := MOVEOBJECT_FORCELOCATION;

//-----------------------------------------------------------------------------
// MoveToCont flags.
//-----------------------------------------------------------------------------

const MOVECONT_JOIN_STACKS   := 0x01;

//-----------------------------------------------------------------------------
