//=====================================================================
//---------------------------------------------------------------------
// Constant Property Names
//---------------------------------------------------------------------
//=====================================================================

const PROP_UNREPAIRABLE                := "UnRepairAble";
const PROP_SUMMONED_FIELD              := "summoned_field";
const PROP_FLAGS                       := "Flags";
const PROP_TEMPFLAGS                   := "#Flags";
const PROP_OWNER                       := "Owner";
const PROP_ITEMHP                      := "ItemHp";
const PROP_ITEM_MAXHP_MOD              := "ItemMaxHpMod";
const PROP_SWINGS                      := "swings";
const PROP_MADE                        := "Made";
const PROP_MOVELOC                     := "#MoveLoc";
const PROP_LAST_TELE                   := "#LastTele";
const PROP_ISECURED                    := "ItemSecured";
const PROP_RAW_SKILL_ARR               := "RawSkillArray";
const PROP_RAW_STAT_ARR                := "RawStatArray";
const PROP_NPC_SPECABL                 := "SpecAbilits";
const PROP_LOGONTIME                   := "logontime";
const PROP_ONLINETIMER                 := "onlinetimer";
const PROP_LASTLOG                     := "LastLog";
const PROP_OLDLASTLOG                  := "OldLastLog";
const PROP_CREATED                     := "Created";
const PROP_QUEST_ITEM                  := "CreatedQuestItem";
const PROP_CREATEDAT                   := "CreatedAt";
const PROP_NOREPORT                    := "#NoReport";
const PROP_LTRG_USE                    := "LastTargUse";
const PROP_LSK_USE                     := "LastSkillUse";
const PROP_CORPSESER                   := "CorpseSerial";
const PROP_SHIPSER                     := "shipserial";
const PROP_SKILLGAIN_WATCHER           := "#SkillGainWatcher";
const PROP_SKILLGAIN_WATCH             := "#SkillGainWatch";
const PROP_USESTH_WATCHER              := "#UseSthWatcher";
const PROP_USESTH_WATCH                := "#UseSthWatch";
const PROP_AISERIAL                    := "AiSerial";
const PROP_LOCKPICKDIFF                := "LockPickDiff";
const PROP_MAXSK                       := "SkMax";
const PROP_SKMASTER                    := "SkMast_";
const PROP_MURDPNDATA                  := "MurdPnData";
const PROP_MURDPNCURSE                 := "#MurdPnCurse";
const PROP_SAFELOGOFF                  := "SafeLogoff";
const PROP_REPORT_MURDER               := "MurdReport";
const PROP_LOGIN_REPORT_MURDER         := "LoginMurdReport";
const PROP_DEATH_TIME                  := "DeathTime";
const PROP_TRITEM_TEMP                 := "TrTempItem";
const PROP_TEMPORARY                   := "Temporary";
const PROP_NPCNEXT_SENDEV              := "#NextSendEv_";
const PROP_PLAYACTION_DELAY            := "#PlayActionDelay";
const PROP_CREATION_TIMER              := "CreationTimer";
const PROP_CREATE_TIME                 := "CreateTime";
const PROP_CHEST_LVL                   := "Lvl";
const PROP_SNDSRC_PARMS                := "SoundParms";
const PROP_SNDSRC_REREAD               := "#ReRead";
const PROP_PV_SELLER                   := "Seller";
const PROP_MOUNTING                    := "Mounting";
const PROP_NPCNEWS                     := "NpcNews";
const PROP_NPCNEWSID                   := "NpcNewsId";
const PROP_WEATHERSTATE                := "WeatherState";
const PROP_MASTER                      := "master";
const PROP_GUILDID                     := "guild_id";
const PROP_NPCTEMP                     := "npctemplate";
const PROP_JAILED                      := "Jailed";
const PROP_PARTS                       := "Parts";
const PROP_PARTS_SERS                  := "PartsSerials";
const PROP_BOUND                       := "Bound";
const PROP_WAR_SIGNED                  := "WarSigned";
const PROP_HARVESTED                   := "Harvested";
const PROP_UNTAMED                     := "UnTamed";
const PROP_SK_SUMMONED                 := "SkillSummoned";
const PROP_CORPSE_OWNER                := "OwnerSerial";

const PROP_FAITHQDATA                  := "FaithQuestData";
const PROP_FAITHSTIME                  := "FaithStartTime";

const PROP_DRUNKNESS                   := "#Drunkness";
const PROP_MAX_DRUNKNESS               := "#MaxDrunkness";

const PROP_LASTCRIMINALSETS            := "LastCriminalSets";

const PROP_AGGRESSORS                  := "#Aggressors";

const PROP_DESCRIPTION                 := "Opis";

const PROP_ROUND_DESTS                 := "WalkDests";

const PROP_NO_LOCKPICK                 := "NoLockpick";
const PROP_NO_UNLOCK                   := "NoUnlock";
const PROP_SHOW_ONLINE                 := "ShowInOnline";
const PROP_GM_KEY                      := "GMKey";
const PROP_PVP_STATUS                  := "PvPStatus";
const PROP_PVP_NO_CHANGE               := "PvPNoChange";

const PROP_STALL                       := "Stall";
const PROP_STALL_OWNER                 := "StallOwner";
const PROP_SHOW_DMG                    := "ShowDmg";
const PROP_TT_DESC                     := "ToolTipDesc";
const PROP_SIGN_HARVOFF                := "HarvSignOff";
const PROP_HARVEST_ONE                 := "HarvOne";

const PROP_FIRST_ATTACKER              := "#FirstAttacker";

const PROP_GAIN_BLOCK                  := "GainBlockTimed";

//---------------------------------------------------------------------
