//-----------------------------------------------------------------------------

const MQUEST_DATA            := ":miniquests:miniquests";
const MQUEST_GLOBAL_PROPS    := "Global";

const MQTYPE_MAXID           := 3;

//-----------------------------------------------------------------------------
// Global Properties
//-----------------------------------------------------------------------------

const MQGPROP_NEXTID         := "NextID";
const MQPROP_CRINFO          := "MQuestCrInfo";
const MQPROP_UPINFO          := "MQuestUpInfo";
const MQPROP_USEINFO         := "MQuestUseInfo";
const MQUEST_TITLE           := "MQs_";
const MQPROP_DATA            := "MiniQuestData";
const MQPROP_TEMP_WDELAY     := "#TempMQWDelay";

//-----------------------------------------------------------------------------
// Quest Properties
//-----------------------------------------------------------------------------

const MQPROP_NPCTEMP         := "NpcTemp";
const MQPROP_TYPE            := "Type";
const MQPROP_TARG            := "Targ";
const MQPROP_LOC             := "Loc";
const MQPROP_TITLE           := "Title";
const MQPROP_ENCRTEXT        := "EncrText";
const MQPROP_MAINTEXT        := "MainText";
const MQPROP_SUCCTEXT        := "SuccText";
const MQPROP_DNPCTEXT        := "DNpcText";
const MQPROP_FLAGS           := "Flags";

//-----------------------------------------------------------------------------
// Quests Config
//-----------------------------------------------------------------------------

const MQUESTS_CFG            := ":miniquests:miniquests";
const MQCFG_TYPE_TITLE       := "Type_";
const MQCFG_GLOBAL           := "Global";
const MQCFG_TNAMES           := "TypeNames";
const MQCFG_MAXQTIME         := "MaxQuestTime";
const MQCFG_ITEMEXPTIME      := "ItemExpTime";
const MQCFG_TEXTVARS         := "TextVars";

//-----------------------------------------------------------------------------
// Quests Created Data Flags (Npc/Player)
//-----------------------------------------------------------------------------

const MQNF_QUEST_GIVEN       := 0x00000001;
const MQNF_QUEST_CREATED     := 0x00000002;
const MQNF_QTARG_CREATED     := 0x00000004;
const MQNF_QCOMPLETED        := 0x00000008;

//-----------------------------------------------------------------------------

const MQN_LOOK_RANGE         := 6;

//-----------------------------------------------------------------------------
